@startuml

title __MODEL's Class Diagram__\n

  namespace app.fachinformatiker.myMashup.model {
    class app.fachinformatiker.myMashup.model.ArgController {
        {static} - producerCount : int
        {static} - consumerCount : int
        {static} - syncCount : int
        {static} + parseArguments()
        {static} + getProducerCount()
        {static} + getConsumerCount()
    }
  }
  

  namespace app.fachinformatiker.myMashup.model {
    class app.fachinformatiker.myMashup.model.Candy {
        - hell : int
        - hope : String
        - producerID : int
        + Candy()
        - createHell()
        - createHope()
        ~ getHell()
        ~ getHope()
        ~ getProducerID()
    }
  }
  

  namespace app.fachinformatiker.myMashup.model {
    class app.fachinformatiker.myMashup.model.Consumer {
        - candyStack : Stack<Candy>
        - consumerID : int
        - sync : int
        - isSync : boolean
        - candyStackSize : int
        + Consumer()
        - candyStackEqualsSync()
        + run()
    }
  }
  

  namespace app.fachinformatiker.myMashup.model {
    class app.fachinformatiker.myMashup.model.Producer {
        - candyStack : Stack<Candy>
        - producerID : int
        {static} - terminator : Terminator
        + Producer()
        + run()
    }
  }
  

  namespace app.fachinformatiker.myMashup.model {
    class app.fachinformatiker.myMashup.model.Terminator {
        + run()
        - leseCodeEin()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
